-- 002_domain_schema.sql — Applications, People, and Documents business tables.
--
-- Conventions:
-- - TEXT primary keys (opaque string IDs generated by services).
-- - TEXT dates (YYYY-MM-DD) and ISO 8601 timestamps, owned by services.
-- - snake_case columns; repositories map to camelCase domain contracts.
-- - Enum membership is enforced by service validation against the canonical
--   shared/domain lists (no CHECK constraints, to avoid a second source of truth).
-- - One Resume + one Cover Letter per application via UNIQUE(application_id,
--   document_type). Document records cascade with their application; managed
--   file copies are removed by services.

CREATE TABLE applications (
  id TEXT PRIMARY KEY,
  company TEXT NOT NULL,
  job_title TEXT NOT NULL,
  location TEXT NOT NULL,
  job_url TEXT NULL,
  date_applied TEXT NOT NULL,
  current_stage TEXT NOT NULL,
  notes TEXT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_applications_current_stage ON applications(current_stage);
CREATE INDEX idx_applications_date_applied ON applications(date_applied DESC);

CREATE TABLE people (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT NULL,
  job_title TEXT NULL,
  person_type TEXT NULL,
  connection_status TEXT NOT NULL,
  linkedin_url TEXT NULL,
  request_sent_date TEXT NULL,
  notes TEXT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_people_connection_status ON people(connection_status);
CREATE INDEX idx_people_request_sent_date ON people(request_sent_date DESC);

CREATE TABLE documents (
  id TEXT PRIMARY KEY,
  application_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL,
  original_file_name TEXT NOT NULL,
  stored_file_name TEXT NOT NULL,
  stored_path TEXT NOT NULL,
  mime_type TEXT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (application_id, document_type)
);

CREATE INDEX idx_documents_application_id ON documents(application_id);
