-- 003_enhancement_sessions.sql — M9 Resume Enhancer session and artifact schema.
--
-- Conventions (matching 002_domain_schema.sql):
-- - TEXT primary keys (opaque string IDs generated by services).
-- - TEXT dates (YYYY-MM-DD) and ISO 8601 timestamps, owned by services.
-- - snake_case columns; repositories map to camelCase domain contracts.
-- - Enum membership is enforced by service validation against the canonical
--   shared/domain lists (no CHECK constraints, to avoid a second source of
--   truth).
-- - One artifact per kind per session via UNIQUE(session_id, artifact_kind).
--   Artifact records cascade with their session; managed file copies are
--   removed by the service layer.
--
-- Lifecycle (PD-M9-011 / PD-M9-012):
-- - `status` is 'in_progress' or 'completed'.
-- - `completed_at` is the retention anchor for completed sessions.
-- - Only completed sessions are retained as Recent Enhancements; incomplete
--   sessions are never retained as enhancement history.

CREATE TABLE enhancement_sessions (
  id TEXT PRIMARY KEY,
  status TEXT NOT NULL,
  job_description TEXT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT NULL
);

CREATE INDEX idx_enhancement_sessions_status ON enhancement_sessions(status);
CREATE INDEX idx_enhancement_sessions_completed_at ON enhancement_sessions(completed_at DESC);

CREATE TABLE enhancement_artifacts (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES enhancement_sessions(id) ON DELETE CASCADE,
  artifact_kind TEXT NOT NULL,
  original_file_name TEXT NOT NULL,
  stored_file_name TEXT NOT NULL,
  stored_path TEXT NOT NULL,
  mime_type TEXT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (session_id, artifact_kind)
);

CREATE INDEX idx_enhancement_artifacts_session_id ON enhancement_artifacts(session_id);